# System utilities
SYSTEM_UTILS=(
  btop
  stow
  fastfetch
  fzf
  eza
  zip
  unzip
  wget
  curl
  tldr
  rustdesk-bin
  zoxide
  jq
)

# Development tools
DEV_TOOLS=(
  aspnet-runtime
  aspnet-targeting-pack
  dotnet-runtime
  dotnet-sdk
  yazi
  bat
  zsh
  neovim
  starship
  tmux
  ghostty
  git
  visual-studio-code-bin
  rider
  github-copilot-cli
  gemini-cli
  opencode-bin
  azure-dev-cli
  azure-cli
  git-delta
)

# System maintenance
MAINTENANCE=(
)

# Desktop environment
DESKTOP=(
  wl-clipboard
  vivaldi
  rustdesk-bin
  obsidian
)

# Media packages
MEDIA=(
)

# Fonts
FONTS=(
  ttf-firacode-nerd 
)

# System services (Requires sudo)
SERVICES=(
)

# User Services (Background processes)
USER_SERVICES=(
)
