"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
palette = "catppuccin_mocha"
format = """
[╭─](overlay0)${env_var.SSH_CONNECTION}$username$hostname${env_var.WORKBENCH_STATE_DIR}$directory$git_branch$git_commit$git_state$git_status$dotnet$docker_context
[╰─](overlay0)$character
"""
right_format = "$cmd_duration$jobs"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[username]
show_always = true
style_user = "bold lavender"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "bold teal"
format = "[@$hostname]($style)"

[env_var.SSH_CONNECTION]
symbol = "󰢹 "
style = "bold sky"
format = "[ $symbol]($style)"

[directory]
truncation_length = 3
truncate_to_repo = false
style = "bold blue"
format = "[ $path]($style) "

[git_branch]
symbol = " "
style = "bold mauve"
format = "[$symbol$branch]($style) "

[git_state]
style = "bold peach"
format = "[$state( $progress_current/$progress_total)]($style) "

[git_status]
style = "bold yellow"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "x${count}"

[dotnet]
symbol = " "
style = "blue"
format = "[$symbol$version]($style) "
detect_extensions = ["sln", "slnx", "csproj", "fsproj", "xproj"]
detect_files = ["global.json", "Directory.Build.props"]

[docker_context]
symbol = " "
style = "overlay1"
format = "[$symbol$context]($style) "
only_with_files = true

[env_var.WORKBENCH_STATE_DIR]
symbol = "󰡨"
style = "bold sky"
format = "[ $symbol]($style)"
description = "Workbench devcontainer"

[cmd_duration]
min_time = 2000
style = "yellow"
format = "[$duration]($style) "

[jobs]
symbol = "󰜎 "
style = "bold sapphire"
