theme = "catppuccin-mocha"
mode = "auto"
vcs = "git"
watch = false
exclude_untracked = false
line_numbers = true
wrap_lines = false
hunk_headers = true
agent_notes = false
transparent_background = false
copy_decorations = false
color_moved = true
